apiVersion: v1
kind: Service             # expose nginx port with a service
metadata:
  namespace: dev-nginx    # add this service in the dev-nginx namespace
  name: my-nginx          # this is the name of the service
  labels:
    app: nginx
spec:
  ports:
  - port: 80               # port exposed
    targetPort: 80         # port in the container
    protocol: TCP
  selector:
    app: nginx
  # type: NodePort
  externalIPs:            # expose this service on these IPs
    - 192.168.3.1         # this is node01.cluster.hk
    - 192.168.3.2         # this is node02.cluster.hk
